// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYWy4vWdz-Vb2kHfQvxwvLIQiNpuKbrTc',
    appId: '1:887130118652:web:2f4f68e54937fc28f13a79',
    messagingSenderId: '887130118652',
    projectId: 'chatappflutter-f7c58',
    authDomain: 'chatappflutter-f7c58.firebaseapp.com',
    storageBucket: 'chatappflutter-f7c58.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAePve3zFuHDxQ6tcA5yzDzdsTDoOQHgHE',
    appId: '1:887130118652:android:42ce376164f63d19f13a79',
    messagingSenderId: '887130118652',
    projectId: 'chatappflutter-f7c58',
    storageBucket: 'chatappflutter-f7c58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP7d9CIieIZJ6WzvrKuvuj6w4WFalOiQc',
    appId: '1:887130118652:ios:99691c921f83daf9f13a79',
    messagingSenderId: '887130118652',
    projectId: 'chatappflutter-f7c58',
    storageBucket: 'chatappflutter-f7c58.appspot.com',
    iosBundleId: 'com.example.chatFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP7d9CIieIZJ6WzvrKuvuj6w4WFalOiQc',
    appId: '1:887130118652:ios:99691c921f83daf9f13a79',
    messagingSenderId: '887130118652',
    projectId: 'chatappflutter-f7c58',
    storageBucket: 'chatappflutter-f7c58.appspot.com',
    iosBundleId: 'com.example.chatFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYWy4vWdz-Vb2kHfQvxwvLIQiNpuKbrTc',
    appId: '1:887130118652:web:7e23d44e10ff9c24f13a79',
    messagingSenderId: '887130118652',
    projectId: 'chatappflutter-f7c58',
    authDomain: 'chatappflutter-f7c58.firebaseapp.com',
    storageBucket: 'chatappflutter-f7c58.appspot.com',
  );

}